### ISSUE TITLE
Referencing errors for scalar values in generate C code

### ISSUE THREAD

**Issue by t-cth** [CSU-CS-Melange/alpha-language#113]
Attempting to compile C code generated by ACC with scalar variables produces referencing errors due to variables being defined as `float *`

![image](https://github.com/user-attachments/assets/6ab774c2-1b65-4ebd-a042-51e0682344bd)

**Comment by lnarmour** [comment]
The problem is in the way the macro statements are printed for scalar variables (i.e., variables with empty domains, and hence no indices). One way to fix this is to change the printExpr function for ArrayAccessExpr to something like this:
```
def static dispatch CharSequence printExpr(ArrayAccessExpr expr) {
		if (expr.indexExpressions.size == 0)
			'''«expr.variableName»[0]'''
		else
			'''«expr.variableName»«FOR index : expr.indexExpressions»[«index.printExpr»]«ENDFOR»'''
	}
```
so that it emits the `[0]` suffix when there are no indices. This is at the following line:  
https://github.com/CSU-CS-Melange/alpha-language/blob/aadbc35a0dc0756511189446588885843c7c1de0/bundles/alpha.codegen/src/alpha/codegen/ProgramPrinter.xtend#L267

Another way to fix it is to change the way the system treats scalars (i.e., set indirection level to 0, verify everywhere else that emits variable related exprs respects this new convention, etc.) but this is a larger change. Perhaps, we can do this down the road, but it is not needed for now.
